FROM python:3.9-slim-buster

RUN apt update && \
    apt install -y socat 
WORKDIR /chall
COPY source/. .
RUN chmod 500 server.py
EXPOSE 1337
CMD ["socat", "-T1600", "TCP-L:1337,fork,reuseaddr", "EXEC:'python3 server.py',pty,stderr,setsid,sane,raw,echo=0"]